version: "3.8"
services:
  postgres_kontor:
    container_name: postgres_kontor
    hostname: postgres_kontor
    image: postgres:latest
    env_file:
      - Site/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data-kontor:/var/lib/postgresql/data"
    networks:
      - main_kontor
    command: -p 5432
  app:
    container_name: app_Nasip
    hostname: app_Nasip
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    volumes:
      - static-data-kontor:/srv/public
      - .:/srv/app_Nasip
    expose:
      - 8000
    depends_on:
      - postgres_kontor
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    networks:
      - main_kontor
      - bridge_network

networks:
  main_kontor:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-kontor:
  static-data-kontor: