version: "3.8"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    env_file:
      - Site/docker.env
    networks:
      - main_nasip
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432

  app:
    container_name: app_Nasip
    hostname: app_Nasip
    build:
      context: .
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    environment:
      - SERVICE_NAME=app
      - "DATABASE=postgres"
    volumes:
      - static-data:/srv/public
      - .:/srv/app
    expose:
      - 8000
    depends_on:
      - postgres
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    working_dir: /srv/app
    networks:
      - main_nasip
      - bridge_network

  nginx_site:
    container_name: nginx_site
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - main_nasip
    volumes:
      - ./nginx/site/nginx.conf:/etc/nginx/conf.d/default.conf


  postgres_fadil:
    container_name: postgres_fadil
    hostname: postgres_fadil
    image: postgres:latest
    env_file:
      - /home/fadilabinew/fadilabi/docker.env
    networks:
      - main_fadil
    ports:
      - "5444:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5444
  app_fadil:
    container_name: app_fadil
    hostname: app_fadil
    build:
      context: .
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - /home/fadilabinew/fadilabi/docker.env
    environment:
      - SERVICE_NAME=app_fadil
      - "DATABASE=postgres_fadil"
    volumes:
      - static-data:/srv/public
      - /home/fadilabinew:/srv/app_fadil
    expose:
      - 8000
    depends_on:
      - postgres_fadil
    command: gunicorn fadilabi.wsgi:application --bind 0.0.0.0:8001
    working_dir: /srv/app_fadil
    networks:
      - main_fadil
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app_fadil
    ports:
      - 81:80
    volumes:
      - /home/fadilabinew/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main_fadil
networks:
  main_fadil:
    driver: bridge

volumes:
  postgresql-data:
  static-data:

