version: "3.8"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    env_file:
      - fadilabi/docker.env
    networks:
      - main_fadil
    ports:
      - "5444:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5444

  app_fadil:
    container_name: app_fadil
    hostname: app_fadil
    build:
      context: .
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - fadilabi/docker.env
    environment:
      - SERVICE_NAME=app_fadil
      - "DATABASE=postgres_fadil"
    volumes:
      - static-data:/srv/public
      - .:/srv/app_fadil
    expose:
      - 8001
    depends_on:
      - postgres
    command: gunicorn fadilabi.wsgi:application --bind 0.0.0.0:8001
    working_dir: /srv/app_fadil
    networks:
      - main_fadil
      - bridge_network

  nginx_fadil:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app_fadil
    ports:
      - 81:80
    networks:
      - main_fadil

networks:
  main_fadil:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data:
  static-data:
