version: "3.8"
services:
  postgres_nasip:
    container_name: postgres_nasip
    hostname: postgres_nasip
    image: postgres:latest
    env_file:
      - Site/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data-nasip:/var/lib/postgresql/data"
    networks:
      - main_nasip
    command: -p 5432
  app:
    container_name: app_nasip
    hostname: app_nasip
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    volumes:
      - static-data-nasip:/srv/public
      - .:/srv/app
    expose:
      - 8000
    depends_on:
      - postgres_nasip
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    working_dir: /srv/app
    networks:
      - main_nasip
      - bridge_network

networks:
  main_nasip:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-nasip:
  static-data-nasip:
