version: "3.8"
services:
  postgres:
    container_name: postgreskontor
    hostname: postgreskontor
    image: postgres:latest
    env_file:
      - Site/docker.env
    ports:
      - "5435:5432"
    volumes:
      - "postgresql-data-kontor:/var/lib/postgresql/data"
    networks:
      - main_kontor
    command: -p 5435
  app_kontor:
    container_name: app_kontor
    hostname: app_kontor
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    volumes:
      - static-data-kontor:/srv/public
      - .:/srv/app_kontor
    expose:
      - 8005
    depends_on:
      - postgres
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8005
    networks:
      - main_kontor
      - bridge_network

networks:
  main_kontor:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-kontor:
  static-data-kontor: