version: "3.8"
services:
  postgres_nasip:
    container_name: postgres_nasip
    hostname: postgres_nasip
    image: postgres:latest
    env_file:
      - Site/docker.env
    networks:
      - main_network
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data-nasip:/var/lib/postgresql/data"
    command: -p 5432

  app_Nasip:
    container_name: app_Nasip
    hostname: app_Nasip
    build:
      context: .
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    environment:
      - SERVICE_NAME=app
      - "DATABASE=postgres"
    volumes:
      - static-data-nasip:/srv/public
      - .:/srv/app
    expose:
      - 8000
    depends_on:
      - postgres_nasip
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    working_dir: /srv/app
    networks:
      - main_network

  nginx_nasip:
    container_name: nginx_nasip
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app_Nasip
    ports:
      - 80:80
    networks:
      - main_network

networks:
  main_network:

volumes:
  postgresql-data-nasip:
  static-data-nasip:

