version: "3.8"

services:
  postgres_nasip:
    container_name: postgres_nasip
    hostname: postgres_nasip
    image: postgres:latest
    env_file:
      - Site/docker.env
    networks:
      - main_network
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5432

  app_nasip:
    container_name: app_nasip
    hostname: app_nasip
    build:
      context: .
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    environment:
      - SERVICE_NAME=app_nasip
      - "DATABASE=postgres_nasip"
    volumes:
      - static-data:/srv/public
      - .:/srv/app
    expose:
      - 8000
    depends_on:
      - postgres_nasip
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    working_dir: /srv/app
    networks:
      - main_network

  nginx_nasip:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app_nasip
    ports:
      - 80:80
    networks:
      - main_network

networks:
  main_network:

volumes:
  postgresql-data:
  static-data:
