version: "3.8"
services:
  postgreskontorfadil:
    container_name: postgreskontorfadil
    hostname: postgreskontorfadil
    image: postgres:latest
    env_file:
      - Site/docker.env
    ports:
      - "5435:5432"
    volumes:
      - "postgresql-data-kontor:/var/lib/postgresql/data"
    networks:
      - main_kontor_fadil
    command: -p 5435
  app_kontor_fadil:
    container_name: app_kontor_fadil
    hostname: app_kontor_fadil
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Site/docker.env
    volumes:
      - static-data-kontor:/srv/public
      - .:/srv/app_kontor_fadil
    expose:
      - 8004
    depends_on:
      - postgreskontorfadil
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8004
    networks:
      - main_kontor_fadil
      - bridge_network

networks:
  main_kontor_fadil:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-kontor:
  static-data-kontor: