# Generated by Django 4.2 on 2023-04-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kontor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisler',
            name='Numara',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='VodafonePaketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('kupur', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('eslestirme_operator_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('eslestirme_operator_tipi', models.CharField(blank=True, max_length=100, null=True)),
                ('eslestirme_kupur', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('Apiden_gelenler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontor.apidencekilenpaketler')),
                ('apiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontor.apiler')),
            ],
            options={
                'verbose_name_plural': 'VodafonePaketler',
            },
        ),
        migrations.CreateModel(
            name='Turkcell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('kupur', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('eslestirme_operator_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('eslestirme_operator_tipi', models.CharField(blank=True, max_length=100, null=True)),
                ('eslestirme_kupur', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('Apiden_gelenler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontor.apidencekilenpaketler')),
                ('apiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontor.apiler')),
            ],
            options={
                'verbose_name_plural': 'TurkcellTam',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakiye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BakiyeHareketleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('onceki_bakiye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sonraki_bakiye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
