# Generated by Django 4.2 on 2023-04-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BakiyeHareketleri',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
