# Generated by Django 4.2 on 2023-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakiyehareketleri',
            name='aciklama',
            field=models.CharField(max_length=255),
        ),
    ]
