# Generated by Django 4.2 on 2023-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0002_siparisler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontorlist',
            name='AlternatifYapilmasin',
            field=models.BooleanField(default=False, verbose_name='Aktif mi ?'),
        ),
    ]
