# Generated by Django 4.2 on 2023-05-01 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0004_siparisler_sonuctarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparisler',
            name='OlusturmaTarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siparisler',
            name='SonucTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
