# Generated by Django 4.2 on 2023-05-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0005_alter_siparisler_olusturmatarihi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakiyehareketleri',
            options={'verbose_name': 'Bayi Listesi', 'verbose_name_plural': 'Bayi Listesi'},
        ),
        migrations.AlterField(
            model_name='durumlar',
            name='durum_id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Askida'), (100, 'İşlemde'), (97, 'İptal ET'), (10, 'Alternatif Paketler Deneniyor'), (98, 'Direk Ana Paketi Gönder'), (998, 'AnaPaketSonucBekler'), (44, 'Sorguda'), (101, 'SorguCevap'), (102, 'SorguTamam'), (31, 'Alternafi Kontrol'), (99, 'Basarili'), (70, 'Alternatif Gönderim Gönder'), (73, 'Alternatif Gönderim Bekliyor'), (71, 'Alternatif islemde'), (72, 'Alternatif Cevap Bekliyor'), (80, 'Alternatif Direk Gönder')], unique=True),
        ),
    ]
