# Generated by Django 4.2 on 2023-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0006_alter_bakiyehareketleri_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banka_adi', models.CharField(max_length=100)),
                ('hesap_sahibi', models.CharField(max_length=100)),
                ('hesap_numarasi', models.CharField(max_length=100)),
                ('sube_kodu', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=50)),
                ('aciklama', models.TextField(blank=True)),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('BayiGormesin', models.BooleanField(default=False, verbose_name='Bayi Gormesin')),
                ('Aktifmi', models.BooleanField(default=True, verbose_name='Aktif mi ?')),
            ],
        ),
    ]
