# Generated by Django 4.2 on 2023-05-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0008_alter_bakiyehareketleri_options_alter_banka_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayi_listesi',
            name='Tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bayi_listesi',
            name='secili_banka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontor.banka'),
        ),
    ]
