# Generated by Django 4.2 on 2023-05-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0009_bayi_listesi_tutar_bayi_listesi_secili_banka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayi_listesi',
            name='secili_banka',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontor.banka'),
        ),
    ]
