# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0010_alter_bayi_listesi_secili_banka'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakiyehareketleri',
            name='onceki_Borc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bakiyehareketleri',
            name='sonraki_Borc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bayi_listesi',
            name='Borc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bayi_listesi',
            name='islem_durumu',
            field=models.CharField(choices=[('islem_sec', 'işlem Türünü Seç'), ('nakit_ekle', 'Nakit/Havele/EFT Bakiye Ekle'), ('borc_ve_bakiye_ekle', 'Hem Borç Hem Bakiye Ekle'), ('bakiye_dus', 'Bakiye Düş'), ('sadece_borc_ekle', 'Sadece Borç Ekle')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakiyehareketleri',
            name='islem_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bakiyehareketleri',
            name='onceki_bakiye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bakiyehareketleri',
            name='sonraki_bakiye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
