# Generated by Django 4.2 on 2023-05-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontor', '0012_alter_bayi_listesi_islem_durumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontorlist',
            name='Urun_Detay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kontorlist',
            name='Urun_adi',
            field=models.CharField(max_length=255),
        ),
    ]
